Fix signature double pipe
stremovskyy/gofondy pull request #2
Opened 2023-12-10 15:46 UTC by burgercking

When trying to get verification link, it returned the following signature string: 
`test|10000|UAH||600.00|/card verification|1396424|Verification Test|8b0d3234-208c-4308-b698-9b0dab36c296|Y|Y`.
As you see it contains double pipe right here: `UAH||600.00`.
This resulted in the following error: Invalid signature.

All we need to do to solve this problem is to check for an empty values when generating the signature.

2023-12-13 08:49 UTC, stremovskyy commented
Hi @burgercking, thank you for your interest and support. This library was developed with significant assistance from Fondy. During the development phase, the DesignID was a required field. However, we find your PR to be very useful.

2023-12-13 09:10 UTC, stremovskyy requested changes
It might be better to combine the check and conditional addition into the slice, as 
`if value, exists := preFiltered[k]; exists && value != ""...`

2023-12-14 10:17 UTC, burgercking commented
@stremovskyy thanks for your answer. Fixed what you requested.

2023-12-14 10:18 UTC, stremovskyy approved these changes

2023-12-14 10:18 UTC, merged